# -*- coding: utf-8 -*-
"""
Converts scripts/golden_vectors.json into the VB.NET golden-vector module
`TokenVisualizer.Core.Tests/GoldenVectors.vb`.

The module embeds, for every pipeline:
  - the tokenizer.json config string (from Python `tokenizer.to_str()`) so the VB test can load
    the SAME config via `Tokenizer.FromJson`, and
  - the reference vectors (text, ids, byte offsets, decoded) recorded from the Python library.

The deepseek pipeline's config is NOT embedded (it is 6 MB and the test loads it from the real
file path); only its vectors are embedded.

Run:  python scripts/emit_golden_vb.py
"""
import json
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
JSON_PATH = os.path.join(SCRIPT_DIR, "golden_vectors.json")
OUT_PATH = os.path.join(
    SCRIPT_DIR, "..", "TokenVisualizer.Core.Tests", "GoldenVectors.vb"
)


def vb_str(s: str) -> str:
    """Emits a VB string literal expression for `s`.

    - `"` is escaped as `""` (VB's only string escape).
    - Control chars (CR, LF, TAB, ...) are emitted as `ChrW(N)` concatenations.
    - Backslashes are literal in VB, so they need no escaping.
    - Printable non-ASCII chars are kept as literal UTF-8 (the .vb file is written as UTF-8).
    """
    if not s:
        return '""'
    parts = []
    cur = []

    def flush():
        if cur:
            parts.append('"' + "".join(cur) + '"')
            cur.clear()

    for ch in s:
        o = ord(ch)
        if o < 0x20 or o == 0x7F:
            flush()
            parts.append("ChrW({})".format(o))
        elif ch == '"':
            cur.append('""')
        else:
            cur.append(ch)
    flush()

    if not parts:
        return '""'
    if len(parts) == 1:
        return parts[0]
    return " & ".join(parts)


def vb_int_array(ids):
    return "New Integer() {" + ", ".join(str(i) for i in ids) + "}"


def vb_offset_array(offsets):
    return "New (Integer, Integer)() {" + ", ".join(
        "({}, {})".format(o[0], o[1]) for o in offsets
    ) + "}"


def vb_text_vector(v, is_last=False):
    members = []
    members.append('                        .Text = {}'.format(vb_str(v["text"])))
    members.append("                        .Ids = {}".format(vb_int_array(v["ids"])))
    members.append(
        "                        .ByteOffsets = {}".format(vb_offset_array(v["byte_offsets"]))
    )
    members.append('                        .Decoded = {}'.format(vb_str(v["decoded"])))
    if "ids_with_specials" in v and v["ids_with_specials"] is not None:
        members.append(
            "                        .IdsWithSpecials = {}".format(
                vb_int_array(v["ids_with_specials"])
            )
        )
    else:
        members.append("                        .IdsWithSpecials = Nothing")
    # VB object initializer members are comma-separated. The collection-initializer element
    # separator comma must be attached to the closing brace line (a `,` alone on a line after a
    # `}` is not valid implicit continuation in VB).
    members_with_commas = [m + "," for m in members[:-1]] + [members[-1]]
    lines = ["                    New TextVector With {"]
    lines.extend(members_with_commas)
    lines.append("                    }" + ("" if is_last else ","))
    return "\n".join(lines)


def write_module(pipelines, out_path=None):
    """Writes the GoldenVectors.vb module for the given pipeline records."""
    if out_path is None:
        out_path = OUT_PATH

    out = []
    out.append("' Auto-generated by scripts/emit_golden_vb.py from scripts/golden_vectors.json.")
    out.append("' Do NOT edit by hand. Regenerate with:  python scripts/emit_golden_vb.py")
    out.append("' These vectors are the authoritative reference produced by the Python `tokenizers`")
    out.append("' library (the Rust core binding). The VB test suite asserts our engine reproduces")
    out.append("' them exactly, making this the definitive Rust-parity gate.")
    out.append("Imports System.Collections.Generic")
    out.append("")
    out.append("Namespace TokenVisualizer.Core.Tests")
    out.append("")
    out.append("    ''' <summary>A single reference text plus its reference tokenization.</summary>")
    out.append("    Public Structure TextVector")
    out.append("        Public Text As String")
    out.append("        Public Ids As Integer()")
    out.append("        Public ByteOffsets As (Integer, Integer)()")
    out.append("        Public Decoded As String")
    out.append("        ''' <summary>ids produced with add_special_tokens=True (Nothing when identical to <see cref=\"Ids\"/> or not recorded).</summary>")
    out.append("        Public IdsWithSpecials As Integer()")
    out.append("    End Structure")
    out.append("")
    out.append("    ''' <summary>Golden vectors for one pipeline plus its tokenizer.json config string.</summary>")
    out.append("    Public NotInheritable Class PipelineVectors")
    out.append("        Public ReadOnly Property Name As String")
    out.append("        Public ReadOnly Property ConfigJson As String")
    out.append("        Public ReadOnly Property VocabSize As Integer")
    out.append("        Public ReadOnly Property Vectors As List(Of TextVector)")
    out.append("")
    out.append("        Public Sub New(name As String, configJson As String, vocabSize As Integer, vectors As List(Of TextVector))")
    out.append("            Me.Name = name")
    out.append("            Me.ConfigJson = configJson")
    out.append("            Me.VocabSize = vocabSize")
    out.append("            Me.Vectors = vectors")
    out.append("        End Sub")
    out.append("    End Class")
    out.append("")
    out.append("    ''' <summary>The authoritative golden vectors recorded from the Python `tokenizers` library.</summary>")
    out.append("    Public Module GoldenVectors")
    out.append("        ' NOTE: Module members are implicitly Shared in VB; do not use the Shared keyword here.")
    out.append("        ' (No blank line may follow the `From {`; the Roslyn VB parser mis-tokenizes the")
    out.append("        ' first element as a line label when it is separated by a blank line.)")
    out.append("        Public ReadOnly Pipelines As New List(Of PipelineVectors) From {")

    for idx, p in enumerate(pipelines):
        out.append("            New PipelineVectors(")
        out.append("                {}, ".format(vb_str(p["name"])))
        out.append("                {}, ".format(vb_str(p.get("config_json", ""))))
        out.append("                {},".format(p["vocab_size"]))
        out.append("                New List(Of TextVector) From {")
        for idx2, v in enumerate(p["vectors"]):
            out.append(vb_text_vector(v, is_last=(idx2 == len(p["vectors"]) - 1)))
        out.append("                }")
        if idx != len(pipelines) - 1:
            out.append("            ),")
        else:
            out.append("            )")

    out.append("        }")
    out.append("    End Module")
    out.append("")
    out.append("End Namespace")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")

    size = os.path.getsize(out_path)
    print("Wrote {} ({} bytes)".format(out_path, size))


def main():
    with open(JSON_PATH, encoding="utf-8") as f:
        pipelines = json.load(f)
    write_module(pipelines)


if __name__ == "__main__":
    main()
