<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>My Project\app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <RootNamespace>TokenVisualizer</RootNamespace>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\TokenVisualizer.Core\TokenVisualizer.Core.vbproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="FluentAvaloniaUI" Version="3.0.0-preview2" />
    <!--Condition below is needed to remove the diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
    <PackageReference Include="Nukepayload2.SourceGenerators.AvaloniaUI" Version="1.0.0" />
  </ItemGroup>
  
  <!--Globbing-->
  <ItemGroup>
    <Compile Remove="**\*.axaml.vb"/>
    <Compile Include="**\*.axaml.vb">
      <DependentUpon>%(Filename)</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
